# Generated by Django 4.1.7 on 2023-06-21 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminCredentials',
            fields=[
                ('username', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('phone', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=350, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientCredentials',
            fields=[
                ('client_id', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('already_called', models.BooleanField(default=False)),
                ('registered_timestamp', models.BigIntegerField(blank=True, null=True)),
                ('registered_date', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('otp_id', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('otp', models.CharField(blank=True, max_length=4, null=True)),
                ('expiry', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh_token', models.CharField(blank=True, max_length=555, null=True)),
                ('user_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='micro_auth_service.admincredentials')),
                ('user_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='micro_auth_service.clientcredentials')),
            ],
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['otp'], name='micro_auth__otp_975daf_idx'),
        ),
        migrations.AddIndex(
            model_name='clientcredentials',
            index=models.Index(fields=['phone', 'email', 'registered_date'], name='micro_auth__phone_0279b4_idx'),
        ),
        migrations.AddIndex(
            model_name='refreshtoken',
            index=models.Index(fields=['user_admin', 'user_client'], name='micro_auth__user_ad_285d94_idx'),
        ),
    ]
