# Generated by Django 4.1.7 on 2023-06-21 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('micro_auth_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ITR',
            fields=[
                ('itr_type', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('itr_name', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('price_in_words', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionDetailsOfClient',
            fields=[
                ('transaction_id', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('transaction_date', models.CharField(max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_details', to='micro_auth_service.clientcredentials')),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(default='')),
                ('date', models.CharField(blank=True, max_length=20, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='micro_auth_service.clientcredentials')),
            ],
        ),
    ]
